name: Beta release

on:
  workflow_dispatch:

jobs:
  release-beta:
    runs-on: macos-latest
    environment: Production
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          ssh-strict: true
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6.0.2"
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workspaces: rust
          target: aarch64-apple-ios-sim,aarch64-apple-ios
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.1.app
      - name: Install Dependencies
        run: bundle install
      - name: Build rust
        run: cd rust && ./build.sh
      - name: Build
        run: bundle exec fastlane beta
        env:
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
          # FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
          # FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          # FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          # FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 120