name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6.0.2"
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install Dependencies
        run: bundle install
      - name: Lint
        run: swift format lint --strict -r -p MinWallet
      - name: Build
        run: bundle exec fastlane build
        env:
          # MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.GH_ACCESS_TOKEN }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}