name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6.0.2"
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/checkout@v4
      - name: Update bundler
        run: gem update
      - name: Install Dependencies
        run: bundle install
      - name: Lint
        run: swift format lint --strict -r -p MinWallet
      - name: Build
        run: bundle exec fastlane build