name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6.0.2"
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-strict: true
      - name: Lint
        run: swift format lint --strict -r -p MinWallet
      - name: Build and test
        run: xcodebuild -scheme MinWallet test