name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: swift-actions/setup-swift@v2
      - uses: actions/checkout@4
      - name: Lint
        run: swift format lint -r -p MinWallet